<?php /** @var $block \SamJ\Instagram\Block\Posts */ ?>
<?php $feed = $block->getFeed(); ?>
<ul>
    <?php foreach ($feed as $item): ?>
        <li>
            <a href="<?php echo $item->getUrl() ?>" target="_blank">
                <img src="<?php echo $item->getImageUrl() ?>" alt="" style="height: 150px;width:150px;"/>
            </a>
            <p><?php echo $item->getText() ?></p>
        </li>
    <?php endforeach; ?>
</ul>
